### ISSUE TITLE
contact/merge with https://github.com/scraly/developers-conferences-agenda ?

### ISSUE THREAD

**Issue by rmannibucau** [javaconferences/javaconferences.github.io#66]
Hi, wonder if https://github.com/scraly/developers-conferences-agenda was contacted and if somehow both sites can converge to something usable by everyone and get a unique location?

**Comment by noctarius** [comment]
No I didn't, since I didn't know about it at the time. Apart from that, this is more specific to Java, while https://github.com/scraly/developers-conferences-agenda is much broader. Not that this is bad, it's just another focus.

**Comment by rmannibucau** [comment]
from my window filtering to java is an UI thing and just requires the PR/submit form has a tag section to enable to filter (like we can filter by location in current javaconferences so I still have hopes ;).
If not I wonder if it would be ok to "scrape"/pull it?
